@file:Suppress("PackageDirectoryMismatch")

object Dependencies {
    const val CORE_KTX = "androidx.core:core-ktx:${Version.CORE_KTX_VERSION}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${Version.APPCOMPAT_VERSION}"
    const val MATERIAL = "com.google.android.material:material:${Version.MATERIAL_VERSION}"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Version.CONSTRAINT_LAYOUT_VERSION}"
    const val LIFECYCLE_LIVEDATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:${Version.LIFECYCLE_VERSION}"
    const val LIFECYCLE_VIEWMODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.LIFECYCLE_VERSION}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${Version.NAVIGATION_VERSION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${Version.NAVIGATION_VERSION}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${Version.SWIPE_REFRESH_LAYOUT_VERSION}"
    const val MOSHI_KOTLIN = "com.squareup.moshi:moshi-kotlin:${Version.MOSHI_VERSION}"
    const val RETROFIT_CONVERTER_MOSHI = "com.squareup.retrofit2:converter-moshi:${Version.RETROFIT_VERSION}"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:${Version.HILT_VERSION}"
    const val HILT_ANDROID_COMPILER = "com.google.dagger:hilt-android-compiler:${Version.HILT_VERSION}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Version.RETROFIT_VERSION}"
    const val OK_HTTP3 = "com.squareup.okhttp3:okhttp:${Version.OK_HTTP3_VERSION}"
    const val OK_HTTP3_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${Version.OK_HTTP3_VERSION}"
    const val RETROFIT_CONVERTER_GSON = "com.squareup.retrofit2:converter-gson:${Version.CONVERTER_GSON_VERSION}"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:${Version.ROOM_VERSION}"
    const val ROOM_COMPILER = "androidx.room:room-compiler:${Version.ROOM_VERSION}"
    const val ROOM_KTX = "androidx.room:room-ktx:${Version.ROOM_VERSION}"
    const val LOTTIE = "com.airbnb.android:lottie:${Version.LOTTIE_VERSION}"
    const val GLIDE = "com.github.bumptech.glide:glide:${Version.GLIDE_VERSION}"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:${Version.GLIDE_VERSION}"
    const val JUNIT = "junit:junit:${Version.JUNIT_4_VERSION}"
    const val JUNIT_KTX = "androidx.test.ext:junit-ktx:${Version.JUNIT_EXTENSION_VERSION}"
    const val TRUTH = "com.google.truth:truth:${Version.TRUTH_VERSION}"
    const val MOCKK = "io.mockk:mockk:${Version.MOCK_VERSION}"
    const val ROBOLECTRIC = "org.robolectric:robolectric:${Version.ROBOLECTRIC_VERSION}"
    const val CORE_TESTING = "androidx.arch.core:core-testing:${Version.ANDROID_ARCH_CORE_TEST_VERSION}"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Version.COROUTINES_TEST_VERSION}"
    const val JUNIT_EXTENSION = "androidx.test.ext:junit:${Version.JUNIT_EXTENSION_VERSION}"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Version.ESPRESSO_CORE_VERSION}"

}